### ISSUE TITLE
Uncaught exception when running preprocess.py

### ISSUE THREAD

**Issue by thomasweng15** [jianglongye/gifs#6]
Hi, I am trying to follow the [Data Preparation](https://github.com/jianglongye/gifs#data-preparation) instructions in the README. I downloaded ShapeNetCoreV1 and am using the provided pre-compiled binary for `intersection`. My system is running Ubuntu 20.04. 

I am running into a problem with running `python dataprocessing/preprocess.py --config configs/shapenet_cars.txt`. When I run this command, I initially see errors like the following, but they do not cause the script to break, so I think they are not critical errors:
```
Error with /checkpoint/thomasweng/IDM/gifs/datasets/shapenet/data/02958343/9e5faa247753ad479289f0a3d35e8de4/model.obj: Traceback (most recent call last):
  File "/private/home/thomasweng/projects/IDM/gifs/dataprocessing/convert_to_scaled_off.py", line 55, in to_off
    input = trimesh.load(path)
  File "/private/home/thomasweng/.conda/envs/gifs/lib/python3.9/site-packages/trimesh/exchange/load.py", line 129, in load
    loaded = load_mesh(file_obj,
  File "/private/home/thomasweng/.conda/envs/gifs/lib/python3.9/site-packages/trimesh/exchange/load.py", line 212, in load_mesh
    results = loader(file_obj,
  File "/private/home/thomasweng/.conda/envs/gifs/lib/python3.9/site-packages/trimesh/exchange/obj.py", line 163, in load_obj
    faces, faces_tex, faces_norm = _parse_faces_fallback(
  File "/private/home/thomasweng/.conda/envs/gifs/lib/python3.9/site-packages/trimesh/exchange/obj.py", line 504, in _parse_faces_fallback
    v.append(int(split[0]))
ValueError: invalid literal for int() with base 10: 'Rear_Spring_Assembly'
```

However, after some time, the script will break with the following error:
```
Traceback (most recent call last):
  File "/private/home/thomasweng/.conda/envs/gifs/lib/python3.9/concurrent/futures/process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/private/home/thomasweng/.conda/envs/gifs/lib/python3.9/concurrent/futures/process.py", line 205, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/private/home/thomasweng/.conda/envs/gifs/lib/python3.9/concurrent/futures/process.py", line 205, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/private/home/thomasweng/projects/IDM/gifs/dataprocessing/boundary_sampling.py", line 63, in generate_labels
    mesh = trimesh.load(input_file)
  File "/private/home/thomasweng/.conda/envs/gifs/lib/python3.9/site-packages/trimesh/exchange/load.py", line 113, in load
    ) = parse_file_args(file_obj=file_obj,
  File "/private/home/thomasweng/.conda/envs/gifs/lib/python3.9/site-packages/trimesh/exchange/load.py", line 627, in parse_file_args
    raise ValueError('string is not a file: {}'.format(file_obj))
ValueError: string is not a file: /checkpoint/thomasweng/IDM/gifs/datasets/shapenet/data/02958343/2cfbf24431d35be39c6936076ed45d0b/model_scaled.off
```

From inspecting the code, it looks like the preprocessing script is supposed to generate this off file, but perhaps it is failing silently. I don't see any errors being logged to stdout. Other .off and label.npz files are being generated successfully. 

Did you encounter this problem or have a workaround? Thank you for your help.

**Comment by jianglongye** [comment]
Apologies for the delay in response. I had forgotten about this issue for a while. It appears `trimesh` is unable to read the provided `model.obj` file. Could you please send the obj file to me so I can investigate further? Also, could you let me know which version of `trimesh` you are using?
